/* The following code was generated by JFlex 1.5.0-SNAPSHOT */



/* --------------------------Codigo de Usuario----------------------- */
package arm.compiler;

import java_cup.runtime.*;
import java.io.Reader;
import java.util.*;
import arm.compiler.BancoInstrucciones;
import arm.compiler.ManejadorErrores;
       

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>alexico.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\2\1\0\1\4\1\1\22\0\1\4\2\0\1\37"+
    "\10\0\1\36\3\0\1\11\1\10\4\11\4\5\1\0\1\3\5\0"+
    "\1\13\1\23\1\24\1\15\1\16\1\6\1\35\1\6\1\32\2\6"+
    "\1\27\1\25\1\14\1\17\1\26\1\34\1\7\1\21\1\33\1\22"+
    "\1\12\1\6\1\30\2\6\1\40\1\0\1\41\3\0\1\13\1\23"+
    "\1\24\1\15\1\16\1\6\1\35\1\6\1\32\2\6\1\27\1\25"+
    "\1\14\1\17\1\26\1\34\1\7\1\21\1\33\1\22\1\12\1\6"+
    "\1\30\2\6\265\0\2\31\115\0\1\20\ufe80\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\6\5\1\1"+
    "\1\5\1\6\3\5\1\7\1\10\1\11\1\12\1\0"+
    "\2\13\1\5\1\14\1\5\1\14\1\5\1\0\1\5"+
    "\2\15\2\5\1\0\3\5\3\0\6\5\1\0\10\5"+
    "\1\0\1\5\1\16\1\17\1\5\1\20\1\21\1\20"+
    "\1\21\1\22\1\23\1\24\2\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\2\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\0\1\47\1\5\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\62\1\61\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\42\0\146\0\42\0\210\0\252"+
    "\0\314\0\356\0\u0110\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba"+
    "\0\u01dc\0\u01fe\0\u0220\0\42\0\42\0\42\0\42\0\146"+
    "\0\u0242\0\42\0\u0264\0\u0264\0\u0286\0\u02a8\0\u02ca\0\u02ec"+
    "\0\u030e\0\u0264\0\u0330\0\u0352\0\u0374\0\u0396\0\u03b8\0\u03da"+
    "\0\u03fc\0\u041e\0\u0440\0\u0462\0\u0484\0\u04a6\0\u04c8\0\u04ea"+
    "\0\u050c\0\u052e\0\u0550\0\u0572\0\u0594\0\u05b6\0\u05d8\0\u05fa"+
    "\0\u061c\0\u063e\0\u0660\0\u0682\0\u06a4\0\252\0\u06c6\0\u06e8"+
    "\0\42\0\42\0\252\0\252\0\252\0\u070a\0\252\0\42"+
    "\0\252\0\u072c\0\252\0\u074e\0\42\0\u0770\0\u0792\0\252"+
    "\0\u07b4\0\252\0\252\0\252\0\42\0\252\0\252\0\252"+
    "\0\252\0\252\0\u07d6\0\252\0\252\0\u07f8\0\u081a\0\u083c"+
    "\0\u085e\0\u0880\0\252\0\252\0\252\0\252\0\42\0\42"+
    "\0\42\0\252\0\252\0\252\0\252\0\252\0\42\0\42"+
    "\0\252\0\252";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\2\7\1\12\1\13\2\10\1\14\1\15\1\16\1\17"+
    "\1\10\1\20\1\21\1\22\1\10\1\23\1\10\1\2"+
    "\4\10\1\24\1\25\1\26\1\27\44\0\1\4\37\0"+
    "\1\30\1\31\1\32\37\30\5\0\1\7\2\10\2\7"+
    "\6\10\1\0\10\10\1\0\4\10\11\0\1\33\2\10"+
    "\2\33\6\10\1\0\10\10\1\0\4\10\11\0\1\34"+
    "\1\10\1\35\1\36\1\34\5\10\1\37\1\40\1\41"+
    "\7\10\1\0\4\10\11\0\1\42\2\10\1\43\1\42"+
    "\6\10\1\0\10\10\1\0\4\10\11\0\1\33\2\10"+
    "\2\33\2\10\1\44\1\45\2\10\1\46\1\47\7\10"+
    "\1\0\4\10\11\0\1\33\2\10\2\33\5\10\1\50"+
    "\1\0\10\10\1\0\4\10\11\0\1\33\1\10\1\51"+
    "\2\33\6\10\1\0\10\10\1\0\4\10\26\0\1\52"+
    "\1\53\7\0\1\54\13\0\1\33\2\10\2\33\6\10"+
    "\1\0\1\10\1\55\1\56\5\10\1\0\1\10\1\57"+
    "\2\10\11\0\1\33\2\10\2\33\2\10\1\60\1\10"+
    "\1\61\1\10\1\0\6\10\1\62\1\10\1\63\1\64"+
    "\2\10\1\65\11\0\1\33\2\10\2\33\6\10\1\0"+
    "\4\10\1\66\3\10\1\0\4\10\11\0\1\33\2\10"+
    "\2\33\1\67\4\10\1\70\1\0\1\10\1\71\4\10"+
    "\1\72\1\10\1\0\4\10\11\0\1\33\2\10\2\33"+
    "\3\10\1\73\2\10\1\74\1\75\7\10\1\0\4\10"+
    "\6\0\1\32\44\0\1\33\2\0\2\33\35\0\1\33"+
    "\2\10\2\33\6\10\1\0\7\10\1\76\1\0\4\10"+
    "\11\0\1\33\2\0\2\34\35\0\1\33\1\10\1\77"+
    "\2\33\6\10\1\0\6\10\1\100\1\10\1\0\4\10"+
    "\27\0\1\101\1\102\22\0\1\33\2\10\2\33\6\10"+
    "\1\0\2\10\1\103\1\104\4\10\1\0\4\10\11\0"+
    "\1\33\2\0\2\42\35\0\1\33\2\10\2\33\3\10"+
    "\1\105\2\10\1\0\10\10\1\0\4\10\11\0\1\33"+
    "\2\10\2\33\3\10\1\106\2\10\1\0\3\10\1\107"+
    "\4\10\1\0\4\10\13\0\1\110\37\0\1\33\1\10"+
    "\1\111\2\33\6\10\1\0\10\10\1\0\4\10\11\0"+
    "\1\33\1\10\1\112\2\33\6\10\1\0\10\10\1\0"+
    "\4\10\11\0\1\33\1\10\1\113\2\33\6\10\1\0"+
    "\10\10\1\0\4\10\27\0\1\114\42\0\1\115\24\0"+
    "\1\116\37\0\1\33\2\10\2\33\6\10\1\0\2\10"+
    "\1\117\5\10\1\0\4\10\11\0\1\33\2\10\2\33"+
    "\6\10\1\0\3\10\1\120\4\10\1\0\4\10\11\0"+
    "\1\33\1\10\1\121\2\33\6\10\1\0\10\10\1\0"+
    "\4\10\11\0\1\33\2\10\2\33\4\10\1\122\1\10"+
    "\1\0\10\10\1\0\4\10\11\0\1\33\2\10\2\33"+
    "\6\10\1\0\10\10\1\0\2\10\1\123\1\10\11\0"+
    "\1\33\2\10\2\33\6\10\1\0\10\10\1\0\1\10"+
    "\1\124\2\10\30\0\1\125\22\0\1\33\2\10\2\33"+
    "\6\10\1\0\3\10\1\126\4\10\1\0\4\10\11\0"+
    "\1\33\2\10\2\33\6\10\1\0\10\10\1\0\1\10"+
    "\1\127\2\10\11\0\1\33\2\10\2\33\2\10\1\130"+
    "\3\10\1\0\5\10\1\131\2\10\1\0\4\10\11\0"+
    "\1\33\2\10\2\33\2\10\1\132\3\10\1\0\10\10"+
    "\1\0\4\10\11\0\1\33\2\10\2\33\1\133\5\10"+
    "\1\0\10\10\1\0\4\10\11\0\1\33\2\10\2\33"+
    "\6\10\1\0\6\10\1\134\1\10\1\0\4\10\11\0"+
    "\1\33\2\10\2\33\1\10\1\135\4\10\1\0\10\10"+
    "\1\0\4\10\11\0\1\33\1\10\1\136\2\33\6\10"+
    "\1\0\10\10\1\0\4\10\13\0\1\137\17\0\1\140"+
    "\17\0\1\33\1\10\1\141\2\33\6\10\1\0\6\10"+
    "\1\142\1\10\1\0\4\10\11\0\1\33\2\10\2\33"+
    "\1\143\5\10\1\0\10\10\1\0\4\10\11\0\1\33"+
    "\2\10\2\33\1\144\5\10\1\0\10\10\1\0\4\10"+
    "\11\0\1\33\2\10\2\33\1\145\5\10\1\0\10\10"+
    "\1\0\4\10\11\0\1\33\2\10\2\33\1\146\5\10"+
    "\1\0\10\10\1\0\4\10\16\0\1\147\41\0\1\150"+
    "\10\0\1\151\23\0\1\33\2\10\2\33\1\152\5\10"+
    "\1\0\10\10\1\0\4\10\11\0\1\33\2\10\2\33"+
    "\1\153\5\10\1\0\2\10\1\154\5\10\1\0\4\10"+
    "\11\0\1\33\2\10\2\33\1\155\5\10\1\0\10\10"+
    "\1\0\4\10\11\0\1\33\2\10\2\33\6\10\1\0"+
    "\2\10\1\156\5\10\1\0\4\10\16\0\1\157\41\0"+
    "\1\160\34\0\1\33\2\10\2\33\1\161\5\10\1\0"+
    "\10\10\1\0\4\10\11\0\1\33\2\10\2\33\1\162"+
    "\5\10\1\0\10\10\1\0\4\10\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2210];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\1\1\1\11\15\1\4\11"+
    "\1\0\1\1\1\11\5\1\1\0\5\1\1\0\3\1"+
    "\3\0\6\1\1\0\10\1\1\0\4\1\2\11\5\1"+
    "\1\11\4\1\1\11\7\1\1\11\11\1\1\0\7\1"+
    "\3\11\5\1\2\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /*  Generamos un java_cup.Symbol para guardar el tipo de token 
        encontrado */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado 
       junto con su valor */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
	
	
	ArrayList<String> instruccion = new ArrayList<String>();
	BancoInstrucciones administrador = new BancoInstrucciones();
	ManejadorErrores moduloErrores = new ManejadorErrores();
	
	private void añadirTermino (String nuevoTermino){
		instruccion.add(nuevoTermino);
	}

	private void añadirInstruccion (){
		administrador.añadirInstruccion(new ArrayList<String>(instruccion));
		instruccion.clear();
	}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnalizadorLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 154) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.out.println("Se ha añadido un error lexico"+yytext());
							moduloErrores.setErrorLexico(yycolumn, yyline, yytext());
          }
        case 51: break;
        case 2: 
          { añadirInstruccion();
          }
        case 52: break;
        case 3: 
          { /* ignora el espacio */
          }
        case 53: break;
        case 4: 
          { añadirTermino (yytext());
                      return symbol(sym.DECIMAL, new Integer(yytext()));
          }
        case 54: break;
        case 5: 
          { //System.out.println("Etiqueta ingresada");
					  añadirTermino (yytext());
                      return symbol(sym.ETIQUETA);
          }
        case 55: break;
        case 6: 
          { añadirTermino ("b");
                          return symbol(sym.B);
          }
        case 56: break;
        case 7: 
          { return symbol(sym.COMA);
          }
        case 57: break;
        case 8: 
          { añadirTermino ("#");	
							return symbol(sym.NUMERAL);
          }
        case 58: break;
        case 9: 
          { //añadirTermino ("[");
                          return symbol(sym.LLAVEIZQ);
          }
        case 59: break;
        case 10: 
          { //añadirTermino ("]");
                          return symbol(sym.LLAVEDER);
          }
        case 60: break;
        case 11: 
          { //System.out.println("Comentario ingresado");
					añadirInstruccion();
          }
        case 61: break;
        case 12: 
          { añadirTermino (yytext().toLowerCase());
                      return symbol(sym.REGISTRO, yytext());
          }
        case 62: break;
        case 13: 
          { añadirTermino (yytext().toLowerCase());
                      return symbol(sym.VECTOR, yytext());
          }
        case 63: break;
        case 14: 
          { añadirTermino ("rrx");
                          return symbol(sym.RRX);
          }
        case 64: break;
        case 15: 
          { añadirTermino ("ror");
                          return symbol(sym.ROR);
          }
        case 65: break;
        case 16: 
          { añadirTermino ("rsb");
                          return symbol(sym.RSB);
          }
        case 66: break;
        case 17: 
          { añadirTermino ("rsc");
                          return symbol(sym.RSC);
          }
        case 67: break;
        case 18: 
          { añadirTermino ("and");
                          return symbol(sym.AND);
          }
        case 68: break;
        case 19: 
          { añadirTermino ("add");
		          System.out.println("Prueba");
                          return symbol(sym.ADD);
          }
        case 69: break;
        case 20: 
          { añadirTermino ("adc");
                          return symbol(sym.ADC);
          }
        case 70: break;
        case 21: 
          { añadirTermino ("asr");
                          return symbol(sym.ASR);
          }
        case 71: break;
        case 22: 
          { añadirTermino ("eor");
                          return symbol(sym.EOR);
          }
        case 72: break;
        case 23: 
          { añadirTermino ("orr");
                          return symbol(sym.ORR);
          }
        case 73: break;
        case 24: 
          { añadirTermino ("sub");
                          return symbol(sym.SUB);
          }
        case 74: break;
        case 25: 
          { añadirTermino ("sbc");
                          return symbol(sym.SBC);
          }
        case 75: break;
        case 26: 
          { añadirTermino ("str");
                          return symbol(sym.STR);
          }
        case 76: break;
        case 27: 
          { añadirTermino ("bne");
                          return symbol(sym.BNE);
          }
        case 77: break;
        case 28: 
          { añadirTermino ("beq");
                          return symbol(sym.BEQ);
          }
        case 78: break;
        case 29: 
          { añadirTermino ("blt");
                          return symbol(sym.BLT);
          }
        case 79: break;
        case 30: 
          { añadirTermino ("bic");
                          return symbol(sym.BIC);
          }
        case 80: break;
        case 31: 
          { añadirTermino ("bgt");
                          return symbol(sym.BGT);
          }
        case 81: break;
        case 32: 
          { añadirTermino ("cmn");
                          return symbol(sym.CMN);
          }
        case 82: break;
        case 33: 
          { añadirTermino ("cmp");
                          return symbol(sym.CMP);
          }
        case 83: break;
        case 34: 
          { añadirTermino ("mvn");
                          return symbol(sym.MVN);
          }
        case 84: break;
        case 35: 
          { añadirTermino ("mov");

                          return symbol(sym.MOV);
          }
        case 85: break;
        case 36: 
          { añadirTermino ("mul");
                          return symbol(sym.MUL);
          }
        case 86: break;
        case 37: 
          { añadirTermino ("mla");
                          return symbol(sym.MLA);
          }
        case 87: break;
        case 38: 
          { añadirTermino ("ldr");
                          return symbol(sym.LDR);
          }
        case 88: break;
        case 39: 
          { añadirTermino ("lsl");
                          return symbol(sym.LSL);
          }
        case 89: break;
        case 40: 
          { añadirTermino ("rorv");
                          return symbol(sym.RORV);
          }
        case 90: break;
        case 41: 
          { añadirTermino ("rolv");
                          return symbol(sym.ROLV);
          }
        case 91: break;
        case 42: 
          { añadirTermino ("addv");

                          return symbol(sym.ADDV);
          }
        case 92: break;
        case 43: 
          { añadirTermino ("eorv");
                          return symbol(sym.EORV);
          }
        case 93: break;
        case 44: 
          { añadirTermino ("subv");
                          return symbol(sym.SUBV);
          }
        case 94: break;
        case 45: 
          { añadirTermino ("strv");
                          return symbol(sym.STRV);
          }
        case 95: break;
        case 46: 
          { añadirTermino ("strb");
                          return symbol(sym.STRB);
          }
        case 96: break;
        case 47: 
          { añadirTermino ("movv");

                          return symbol(sym.MOVV);
          }
        case 97: break;
        case 48: 
          { añadirTermino ("ldrb");
                          return symbol(sym.LDRB);
          }
        case 98: break;
        case 49: 
          { añadirTermino ("lsrv");
                          return symbol(sym.LSRV);
          }
        case 99: break;
        case 50: 
          { añadirTermino ("lslv");
                          return symbol(sym.LSLV);
          }
        case 100: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
