
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 21 21:38:26 PDT 2017
//----------------------------------------------------

package arm.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REGISTRO = 5;
  public static final int STR = 37;
  public static final int LDR = 39;
  public static final int SBC = 18;
  public static final int BNE = 45;
  public static final int LLAVEDER = 3;
  public static final int MVN = 21;
  public static final int ORR = 20;
  public static final int CMP = 24;
  public static final int CMN = 25;
  public static final int BGT = 46;
  public static final int B = 43;
  public static final int AND = 9;
  public static final int LSL = 28;
  public static final int EOR = 10;
  public static final int MOV = 26;
  public static final int DECIMAL = 48;
  public static final int MOVV = 27;
  public static final int EOF = 0;
  public static final int EORV = 11;
  public static final int ASR = 31;
  public static final int error = 1;
  public static final int MUL = 23;
  public static final int COMA = 2;
  public static final int ADD = 15;
  public static final int ADC = 17;
  public static final int MLA = 36;
  public static final int VECTOR = 6;
  public static final int LDRV = 40;
  public static final int BLT = 47;
  public static final int STRV = 38;
  public static final int ADDV = 16;
  public static final int RSC = 19;
  public static final int RSB = 14;
  public static final int LLAVEIZQ = 4;
  public static final int SUBV = 13;
  public static final int ROLV = 35;
  public static final int NUMERAL = 8;
  public static final int RRX = 32;
  public static final int BIC = 22;
  public static final int RORV = 34;
  public static final int ROR = 33;
  public static final int LDRB = 42;
  public static final int LSLV = 29;
  public static final int STRB = 41;
  public static final int ETIQUETA = 7;
  public static final int LSRV = 30;
  public static final int SUB = 12;
  public static final int BEQ = 44;
}

