
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 14 22:25:35 CST 2017
//----------------------------------------------------

package arm.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REGISTRO = 5;
  public static final int STR = 28;
  public static final int LDR = 29;
  public static final int SBC = 14;
  public static final int BNE = 34;
  public static final int MVN = 17;
  public static final int LLAVEDER = 3;
  public static final int ORR = 16;
  public static final int CMP = 20;
  public static final int CMN = 21;
  public static final int BGT = 35;
  public static final int B = 32;
  public static final int AND = 8;
  public static final int LSL = 23;
  public static final int EOR = 9;
  public static final int MOV = 22;
  public static final int DECIMAL = 37;
  public static final int EOF = 0;
  public static final int ASR = 24;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int COMA = 2;
  public static final int ADD = 12;
  public static final int ADC = 13;
  public static final int MLA = 27;
  public static final int BLT = 36;
  public static final int RSC = 15;
  public static final int RSB = 11;
  public static final int LLAVEIZQ = 4;
  public static final int NUMERAL = 7;
  public static final int RRX = 25;
  public static final int BIC = 18;
  public static final int ROR = 26;
  public static final int LDRB = 31;
  public static final int STRB = 30;
  public static final int ETIQUETA = 6;
  public static final int SUB = 10;
  public static final int BEQ = 33;
}

