/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arm;

import arm.assembler.Decodificacion;

/**
 *
 * @author jaam
 */
public class AssembleFrame extends javax.swing.JFrame {
    
    Decodificacion ensamblador = new Decodificacion();

    public AssembleFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Machine Code");
        
        //Impresion del ensamblaje
        String ensamblaje = "";
        ensamblaje = ensamblador.obtenerEnsamblaje();        
        jTextAreaInstruccionesEnsambladas.setText(ensamblaje);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //ensamblador.borrarEnsamblaje();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInstruccionesEnsambladas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaInstruccionesEnsambladas.setEditable(false);
        jTextAreaInstruccionesEnsambladas.setColumns(20);
        jTextAreaInstruccionesEnsambladas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaInstruccionesEnsambladas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInstruccionesEnsambladas;
    // End of variables declaration//GEN-END:variables
}
